import "./globals.css";
import "@flaticon/flaticon-uicons/css/all/all.css";


export const metadata = {
  title: "Life In Dots",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
        </body>
    </html>
  );
}
